storage:
  srv_path: "etc/srv"
  srv_db_name: "service.db"
  usr_path: "etc/usr"

log:
  stdio: true
  file: true
  file_path: "etc/log"
  syslog: false
  systag: "srv"

network:
  http:
    enable: true
    listen: "0.0.0.0"
    port: "8080"
    read_timeout: "15s"
    write_timeout: "15s"
